* Requirements before course

** Operating system
- Preferred OS are unix based (mac/linux)
- Windows users will need to install [[http://www.cygwin.com][Cygwin]].

** Software
- Install R and Rstudio (or other editor of their choice).
- git
- make
- set up a github/bitbucket account? 

* Ideal course?

** Topics
*** shell
As in [[http://software-carpentry.org/4_0/shell/][other boot-camps]].

*** Version control
As in [[http://software-carpentry.org/4_0/vc/index.html][other boot-camps]].
The students will create their own repo on bitbucket (or github?).

*** Automating task
Using =make=, as in previous [[http://software-carpentry.org/4_0/make/index.html][boot-camps]]. 
Barry mentioned [[http://www.scons.org/][scons]] (python based), which is more modern. 
But =make= is so much used that it may be preferable. 

*** Reproducible research
With Rmarkdown (easier to understand than latex). I believe Rstudio has some nice facilities for Rmarkdown. 

*** Testing 

SJE interested in tackling the testing section.  Will need to explore
the /testthat/ package. (There is also [[http://cran.r-project.org/web/packages/RUnit/index.html][Runit]]).

If we do any package development (I doubt, though), =testthat=/=Runit= 
are cetainly important to illustrate. But what if we don't do any package stuff?
=testthat= can still be used (=test_file=, =test_dir=, ...) (not sure about =Runit=), 
but is it worth adding this additional complexity (new package, new functions, ...). 
Is it not better to concentrate on more basic/essential aspects, like numerical analysis, 
=identical=, =all.equal= (instead or =all(x == y)=), ...


*** Programming with R
Can we take the recent python course @ manchester and s/python/R/
updating where need be.

Specific topics for R: =apply= et al, graphics. Emphasis on data manipulation/analysis.

*** Other about programming
Debugging and profiling. 


** Other
- the [[https://github.com/jennybc/swcR_duke][Duke R boot camp]]

* Teching needs

Can we find about 4 teachers to cover 1/2 day each?  
Solicit help from the mailing list... 


